### ISSUE TITLE
gg是否支持go-gost

### ISSUE THREAD

**Issue by novohool** [mzz2017/gg#60]
https://github.com/go-gost/gost

比如客户端为
```
services:
- name: client
  addr: ":1080"
  handler:
    type: socks5
    chain: chain-0
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: gg.org:443
      connector:
        type: socks5
        auth:
          username: gg
          password: gg@Gost
      dialer:
        type: mwss
        metadata:
          host: "gg.org" 
          path: "/ws" 
          header: {}
```
